### ISSUE TITLE
Eval4NLP 2023 Ingestion

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#3081]
@anthology-assist is there any update on the Eval4NLP@AACL ingestion, or can we somehow provide more information?

_Originally posted by @flipz357 in https://github.com/acl-org/acl-anthology/issues/2791#issuecomment-1937847436_

**Comment by flipz357** [comment]
The relevant material had been linked by @kfnks in this [comment](https://github.com/acl-org/acl-anthology/issues/2791#issuecomment-1926848848). To quote: https://www.dropbox.com/scl/fi/wu74zqzgdp34p0ifreznd/papers.yml?rlkey=uqtttxtbnuzrl4tl1jlwfqjs1&dl=0

**Comment by anthology-assist** [comment]
@kfnks @flipz357 The ingestion material for eval4nlp is incomplete. I saw that it's in aclpub2 format -- We need all .yaml files and everything in the `expected output` section specified [here](https://github.com/rycolab/aclpub2). Let me know if anything is unclear.

**Comment by flipz357** [comment]
(ping @danieldeutsch)

**Comment by danieldeutsch** [comment]
Can you be more specific about what is missing? I zipped the output from the aclpub2 tool. This is what I delivered to the publication chairs: https://drive.google.com/file/d/1AOKfrBeEIL1sViZWuAfbsfUw1actbFpg/view?pli=1

**Comment by flipz357** [comment]
@anthology-assist I also see all the required `.yml` files in the zip provided by @danieldeutsch. It's now also not clear to me what's exactly missing.

**Comment by flipz357** [comment]
@anthology-assist Could you comment on what is still missing?

**Comment by mjpost** [comment]
I'm not sure what's missing and hope @anthology-assist will respond soon. Can you run [this script](https://github.com/acl-org/acl-anthology/blob/master/bin/aclpub2_format_check.py) which might turn up something?

**Comment by flipz357** [comment]
Thanks @mjpost, maybe @anthology-assist is busy or away at the moment. @danieldeutsch could you try running the script?

**Comment by flipz357** [comment]
@anthology-assist @mjpost I now tried running the script. It seems that everything is fine:

```
✓ Found anth/inputs/conference_details.yml
✓ Found anth/inputs/papers.yml
✓ Found PDF file anth/watermarked_pdfs/1.pdf
✓ Found PDF file anth/watermarked_pdfs/2.pdf
✓ Found PDF file anth/watermarked_pdfs/3.pdf
✓ Found PDF file anth/watermarked_pdfs/4.pdf
✓ Found PDF file anth/watermarked_pdfs/5.pdf
✓ Found PDF file anth/watermarked_pdfs/6.pdf
✓ Found PDF file anth/watermarked_pdfs/7.pdf
✓ Found PDF file anth/watermarked_pdfs/8.pdf
✓ Found PDF file anth/watermarked_pdfs/9.pdf
✓ Found PDF file anth/watermarked_pdfs/10.pdf
✓ Found PDF file anth/watermarked_pdfs/11.pdf
✓ Found PDF file anth/watermarked_pdfs/12.pdf
✓ Found PDF file anth/watermarked_pdfs/13.pdf
✓ Found PDF file anth/watermarked_pdfs/14.pdf
✓ Found PDF file anth/watermarked_pdfs/15.pdf
✓ Found PDF file anth/watermarked_pdfs/16.pdf
✓ Found PDF file anth/watermarked_pdfs/17.pdf
✓ Found PDF file anth/watermarked_pdfs/18.pdf
✓ Found PDF file anth/watermarked_pdfs/19.pdf
✓ Found frontmatter at anth/watermarked_pdfs/0.pdf
```

**Comment by danieldeutsch** [comment]
Thanks Juri for running the command! The last issue that I was made aware of was that papers.yml was incorrectly formatted. In the original delivery of the proceedings, I just used the output of the aclpub2 tool. I was then told it was not correctly formatted. The generated file did not conform to the expected output described in the aclpub2 Readme, so I manually edited the file to match the expected format as best as I could.

If any yml file is in an unexpected format, there were only 19 papers so I think just manually correcting the file makes the most sense to me to get this resolved.

**Comment by mjpost** [comment]
The validation script doesn't (yet) check for internal formatting, so it's possible there is still something wrong. @anthology-assist can handle this shortly.

**Comment by mjpost** [comment]
There is a preview [here](https://preview.aclanthology.org/eval4nlp-2023-ingestion/volumes/2023.eval4nlp-1/); can you please take a look? Note that we only generate preview bibtex for the first three items.

**Comment by flipz357** [comment]
Thanks, it all looks good, except for this weird author name here
![image](https://github.com/acl-org/acl-anthology/assets/59831412/927f788b-f6d6-4df6-bfea-fca95c6ef507)

I think it could be a bug from `conference_details.yml`. @danieldeutsch do you know what is this "John Walker" :-) 

How important is it to correct, or can it be also corrected later?

**Comment by flipz357** [comment]
I've corrected the names in the file now manually, can you replace the other one?

conference_details.yml
```
anthology_venue_id: Eval4NLP
start_date: 2023-11-01
end_date: 2023-11-01
isbn: 979-8-89176-021-9
location: Bali, Indonesia
editors:
  - first_name: Daniel
    last_name: Deutsch
  - first_name: Rotem
    last_name: Dror
  - first_name: Steffen
    last_name: Eger
  - first_name: Yang
    last_name: Gao
  - first_name: Christoph
    last_name: Leiter
  - first_name: Juri
    last_name: Opitz
  - first_name: Andreas
    last_name: Rücklé
publisher: Association for Computational Linguistics
watermark_book_title: Proceedings of the 4th Workshop on Evaluation and Comparison of NLP Systems
```
