### ISSUE TITLE
Presentation link not working

### ISSUE THREAD

**Issue by tuhinjubcse** [acl-org/acl-anthology#549]
https://www.aclweb.org/anthology/people/t/tuhin-chakrabarty/

https://www.aclweb.org/anthology/N19-1054/

Presentation : https://github.com/tuhinjubcse/tuhinjubcse.github.io/blob/master/IMHO%20Fine-Tuning%20Improves%20Claim%20Detection%20.pdf

**Comment by mjpost** [comment]
Thanks for reporting. I corrected the file, and you can download it here: https://www.aclweb.org/anthology/attachments/N19-1054.Presentation.pdf

The problem is twofold:

1. This user had uploaded a Github URL that wasn't downloaded correctly by our automated attachment ingestion.

2. In the Anthology build, we are apparently appending attachment URLs instead of calling `.format()`. See this line in the generated YAML:

```yaml
  attachment:
  - filename: N19-1054.Presentation.pdf
    type: presentation
    url: https://www.aclweb.org/anthology/attachments/{}/N19-1054.Presentation.pdf
```
